### PR TITLE
FIx: remove funders from query for none voting grant

### PR DESCRIPTION
**Pull request by Agill-Sheron**
https://linear.app/geyser/issue/GYS-7136/modify-grant-query-to-remove-project-funders

### CODE REVIEW

**Review by sajald77 — APPROVED** [review]
Looks good, but make sure you resolve the ones on the other PR, as I see those changes here as well.

**Comment by Agill-Sheron** [comment]
> Looks good, but make sure you resolve the ones on the other PR, as I see those changes here as well.

Hey Sajal, I'm not sure I understand which PRs you are referring to

**Comment by Agill-Sheron** [comment]
> > Looks good, but make sure you resolve the ones on the other PR, as I see those changes here as well.
> 
> Hey Sajal, I'm not sure I understand which PRs you are referring to 
> 

Would it be this one: https://linear.app/geyser/issue/GYS-6964/display-pending-grant-applicants-in-grant-page

**Comment by sajald77** [comment]
> > > Looks good, but make sure you resolve the ones on the other PR, as I see those changes here as well.
> > 
> > 
> > Hey Sajal, I'm not sure I understand which PRs you are referring to
> 
> Would it be this one: https://linear.app/geyser/issue/GYS-6964/display-pending-grant-applicants-in-grant-page

I meant the Amount refunded cap. But it looks good now.

**Pull request merged**
